name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libcred:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Compile and run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install system deps for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y gnome-keyring dbus-x11

      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
