name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libcred:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Compile and run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12

      - name: Install system deps for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y gnome-keyring dbus-x11

      - name: Prepare Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run : |
          eval "$(dbus-launch --sh-syntax)"
          mkdir -p ~/.cache
          mkdir -p ~/.local/share/keyrings
          eval "$(printf '\n' | gnome-keyring-daemon --unlock)"
          eval "$(printf '\n' | /usr/bin/gnome-keyring-daemon --start)"
          
      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        if: matrix.os != 'ubuntu-latest'
        with:
          action: test
          directory: build
          ninja-version: 1.10.2
