name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libcred:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Compile and run tests
    steps:
      - uses: actions/checkout@v2

      - name: Install system deps for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y gnome-keyring dbus-x11

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      - name: Build
        shell: micromamba-shell {0}
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            export $(dbus-launch)
            export $(echo 'somerandompass' | gnome-keyring-daemon --unlock)
          fi
          meson setup builddir
          cd builddir
          ninja
          ninja test
          ./ex1
