name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libcred:
    defaults:
      run:
        shell: bash -leo pipefail {0}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Compile and run tests
    steps:
      - uses: actions/checkout@v2

      - name: Install system deps for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y gnome-keyring dbus-x11

      - name: Install mamba
        if: matrix.os == 'ubuntu-latest'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/environment.yml
          cache-environment: true
          post-cleanup: 'all'
          init-shell: bash

      - name: Build ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
            export $(dbus-launch)
            export $(echo 'somerandompass' | gnome-keyring-daemon --unlock)
            meson setup builddir
            cd builddir
            ninja
            ninja test
        shell: bash {0}
      
      - name: Build windows and macos
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          ninja-version: 1.10.2
